package com.markme.app.data

import android.content.Context
import app.cash.sqldelight.driver.android.AndroidSqliteDriver
import com.markme.data.Database // <-- This import is auto-generated by SQLDelight

// --- START FIX ---
// Convert DatabaseManager from a class to an object to make it a singleton
object DatabaseManager {

    private var databaseInstance: Database? = null

    /**
     * Creates (if necessary) and returns the singleton Database instance.
     *
     * @param context An application context is required to create the driver
     * on first call.
     * @return The singleton Database instance.
     */
    fun getInstance(context: Context): Database {
        // Use standard double-check locking for thread-safety
        return databaseInstance ?: synchronized(this) {
            databaseInstance ?: buildDatabase(context).also {
                databaseInstance = it
            }
        }
    }

    private fun buildDatabase(context: Context): Database {
        val driver = AndroidSqliteDriver(
            schema = Database.Schema, // <-- This is from the import
            context = context.applicationContext, // Use application context
            name = "MarkMe.db"
        )
        return Database(driver) // <-- This is from the import
    }
}
// --- END FIX ---